### ISSUE TITLE
Lxdm propose le clavier de_CH même si on demande une autre locale.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/core#110]
J'ai pu constater la présence en plus de la locale de_CH en allant dans le menu déroulant "langue / Plus..." 

Cf la capture d'écran ci-dessous.

![lxdm-double-langue](https://cloud.githubusercontent.com/assets/8571419/16894005/60092522-4b49-11e6-9ed1-a4c6f9c65547.png)

**Comment by tnut** [comment]
Sera corrigé dans les prochaines ISO (8.2-rc1)

**Comment by FredBezies** [comment]
Corrigé dans mes tests préliminaires de la RC1. Je verrai avec la RC2 d'ici demain.

**Comment by FredBezies** [comment]
Corrigé en effet. Au revoir le bug :)
