### ISSUE TITLE
get syslinux: dependence non installée

### ISSUE THREAD

**Issue by guy2009** [NuTyX/core#113]
Sous NuTyX 8.2-beta-2, un get syslinux n'installe pas le paquet mtools

 `
guy [ ~ ]$ get syslinux
/var/lib/pkg/depot/cli-extra/syslinux/.PKGREPO
/var/lib/pkg/depot/cli-extra/syslinux/syslinux1467922677x86_64.cards.tar.xz
1440872 Bytes - 1045047 Bytes/Sec - 100% - 0 Sec remain emain 
Retrieve info about the 295 packages: 100 %
ADD    : syslinux 6.03-1, 375 files: 100 %
guy [ ~ ]$ 
guy [ ~ ]$ sudo syslinux /dev/sdb1
sh: mcopy: command not found
syslinux: failed to create ldlinux.sys

guy [ ~ ]$ get mtools
/var/lib/pkg/depot/cli/mtools/.PKGREPO
/var/lib/pkg/depot/cli/mtools/mtools1467317162x86_64.cards.tar.xz
82076 Bytes - 288797 Bytes/Sec - 100% - 0 Sec remain c remain 
Retrieve info about the 296 packages: 100 %
ADD    : mtools 4.0.18-1, 37 files: 100 %

guy [ ~ ]$ sudo syslinux /dev/sdb1
guy [ ~ ]$
 `

**Comment by tnut** [comment]
J'ai corrigé le port. c'est OK ?

**Comment by guy2009** [comment]
Salut,

Oui, c'est OK.
merci.

B�t,
Guy

On Thu, 04 Aug 2016 09:00:42 -0700
tnut <notifications@github.com> wrote:

> J'ai corrig� le port. c'est OK ?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NuTyX/core/issues/113#issuecomment-237599265

-- 
Guy Toussaint

**Comment by tnut** [comment]
Merci de fermer l'issue si résolu
