### ISSUE TITLE
Modification_script_runmebeforepass1

### ISSUE THREAD

**Issue by oouuppss** [NuTyX/core#120]
Comme signalé sur le canal dans le script  "core/scripts/runmebeforepass1" on utilise /home/lfs et $HOME en même temps.
Donc du coup autant utiliser juste $HOME qui me parait plus judicieux au cas ou l'user aurrait une organisation exotique de l'emplacement de ses homes.
Ci-joint ma première contribution avec un patch diff !
[patch.runmebeforepass1.txt](https://github.com/NuTyX/core/files/550546/patch.runmebeforepass1.txt)

**Comment by tnut** [comment]
merci pour ton issue, tu peux essayer de faire un pull request

**Comment by oouuppss** [comment]
Ok j'essaye.

**Comment by tnut** [comment]
fixed
