### ISSUE TITLE
Dans qt-base ...

### ISSUE THREAD

**Issue by Pierre-NuTyX** [NuTyX/core#123]
Dans qt-base :

j'ai mis 

```
QT5PREFIX=/usr
QT5BINDIR=$QT5PREFIX/bin/qt

```
et

```
cat > $PKG/etc/profile.d/qt.sh << EOf
# Begin /etc/profile.d/qt.sh
QT5PREFIX=$QT5PREFIX
QT5DIR=$QT5PREFIX
QT5BINDIR=$QT5PREFIX/bin/qt
export QT5PREFIX QT5BINDIR QT5DIR
# End /etc/profile.d/qt.sh
EOf
```

Ce ne devrait pas plutôt être QTPREFIX, QTBINDIR ....... à la place de QT5PREFIX, QT5BINDIR ?

**Comment by tnut** [comment]
non, par contre le cat va pas remplacer la variable $QT5PREFIX par son contenu
et donc il me semble que le fichier contiendra:
# Begin /etc/profile.d/qt.sh
QT5PREFIX=
QT5DIR=
QT5BINDIR=/bin/qt
export QT5PREFIX QT5BINDIR QT5DIR
# End /etc/profile.d/qt.sh

**Comment by tnut** [comment]
non, mais à vérifier
