### ISSUE TITLE
Xorg freeze intel/amd

### ISSUE THREAD

**Issue by grosbedos** [NuTyX/core#124]
Hi,

I have a laptop with an integrated intel video card. I have also a discrete gpu, amd/radeon.

With NuTyX 8.x, no problem, module radeon is loaded, but not used. It's working.
With NuTyX 9.0RC1, radeon is loaded, but xorg crash. Xorg doesn't load radeon, it's not written in the log, i have just found the word "intel" in the log.

When X launch, i have a black screen with a cursor at the top left of the screen, not blinking, and the laptop doesn't respond. Can't get in a tty, keyboard doesn't work, led on keyboard too.. But logging keep working. I have to push the power button.

No usefull information in log, no kernel panic, no error..

If i blacklist radeon, it's working.

And secondly, you have make a link in /root which is pointing to /etc/modprobe.d, but the directory /etc/modprobe.d doesn't exist ;)

Best regards.

**Comment by tnut** [comment]
Thanks a  lot for your feedbacks. About radeon and kernel, I guess that's the only way. About the link, I will remove it you right
