### ISSUE TITLE
tor problem

### ISSUE THREAD

**Issue by guy2009** [NuTyX/core#125]
Je n'arrive pas à me connecter à tor:
`TorManager Tor controller connect error: error: [Errno 111] Connection refused in TorManager.py line 165`

dans le post-install, la commande
`groupadd -g 43`
est en conflit avec le fichier /etc/group du paquet nutyx
dans lequel le group id 43 est attribué au user dovenull

La post-install met donc
`groupadd: GID '43' already exists`

**Comment by tnut** [comment]
Commité la correction
