### ISSUE TITLE
qt.sh

### ISSUE THREAD

**Issue by Pierre-NuTyX** [NuTyX/core#128]
Dans /etc/profile.d/qt.sh ... où est définie QT5PREFIX ?

Ne serait-ce pas mieux ainsi ?
```
# Begin /etc/profile.d/qt.sh
QT5PREFIX=/usr
QT5DIR=$QT5PREFIX
QT5BINDIR=$QT5PREFIX/bin/qt
export QT5PREFIX QT5BINDIR QT5DIR
pathappend $QT5BINDIR
# End /etc/profile.d/qt.sh
```

**Comment by tnut** [comment]
C'est pas necessaire, pour 2 raisons:

- QT5PREFIX  est seulement utilisée pour la compilation de qt
- le script qt.sh ne sera jamais dispo avant la compilation du premier port de qt
