### ISSUE TITLE
Firefox et HTTPS Everywhere

### ISSUE THREAD

**Issue by guy2009** [NuTyX/core#131]
Bonjour tnut, 

J'utilise l'extension HTTPS Everywhere avec firefox.
Malheureusement, sous NuTyX, cela semble ne pas fonctionner, contrairement à d'autres distributions...

J'ai testé averc
   NuTyX 9.0 stable32 bits firefox  53.0.3
   FreeBSD 11.0 64bits firefox 53.0.2

Bàt,
Guy

**Comment by tnut** [comment]
Peux tu essayer avec la version 54.0
