### ISSUE TITLE
Suggestion: documentation process.

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#14]
Just a suggestion I had to simplify your documentation process.

I saw that you use currently a lot of 'hard coded' names / links and some of them are dead.

Maybe instead of: <http://www.nutyx.org/en/installation.html>

1.

`dd if=NuTyX_x86_64-houaphan-8.0.iso of=/dev/sdX` **you could keep things more general**
`dd if=path-to-NuTyX_current.iso of=/dev/sdX`

2.  

`git clone git://github.com/NuTyX/houaphan.git`

Seems that next time you have a new release which might not be named 'houaphan' you will have to updated everything.

Not sure if I see that correctly but maybe keeping it more general would be an advantage.

**Comment by tnut** [comment]
houaphan was indeed the code name. You probably right. this "hard coded" names are giving me a hard time (sometimes) Would it means we need to rename this git to ... current for example ?

**Comment by peter1000** [comment]
>  Would it means we need to rename this git to ... current for example ?

Yes  

I think it would be better to call it: **NuTyX** and develop it on the *master* branch.  

When you make a new release you could just "Tag it  a new release" or create an other branch:  `NuTyX v.8` or even `houaphan`.

But in the documentation I would keep it simple. Just a suggestion.

Cheers
P

**Comment by peter1000** [comment]
BTW: I saw at [distrowatch.com](http://distrowatch.com/table.php?distribution=nutyx) that *NuTyX* is refered to as: 

```
French Linux distribution
```

and also in [Wiki Rolling_release](https://en.wikipedia.org/wiki/Rolling_release)

```
NuTyX Linux is a French Linux distribution
```

This might discourage some none French speakers to look at it.

**Comment by peter1000** [comment]
Just for info: I will test some installations and update for you some parts of the documentation.

**Comment by tnut** [comment]
I like it

**Comment by peter1000** [comment]
hi @tnut,

Could you create a new repository **NuTyX**  (or rename this) than any changes could be made there.

See also: [Renaming a repository](https://help.github.com/articles/renaming-a-repository/)

**Comment by tnut** [comment]
Why not working with branches ?

**Comment by peter1000** [comment]
@tnut 

> houaphan was indeed the **code name**

I think working with branches is good but **houaphan** should be actually a branch of **NuTyX**.

Just a thought, but its your repository and you should feel comfortable with it :)


Anyway: I'm doing some work on the `setup-nutyx` - I read somewhere that you do not indent to make it a bit more advanced.

I have also set up a repository for: [Unofficial-NuTyX-docs](https://github.com/peter1000/Unofficial-NuTyX-docs) where I plan to write some of the things I encounter.

I write all my documentation in markdown and use: [MkDocs](https://github.com/mkdocs/mkdocs) to generate the html. I find that much faster and easier to maintain.

**Comment by tnut** [comment]
For the wrong info on DW, don't hesitate to contact Jesse Smith  distro at distrowatch dot com At wiki.rollingrelease I don't know who should I contact

**Comment by peter1000** [comment]
Maybe we should leave this open until the docs are a bit more up-to-date.

**Comment by tnut** [comment]
For the release of 8.1, I decide to rename as you suggest install-houaphan and enter-houaphan in install-nutyx and enter-nutyx

**Comment by peter1000** [comment]
Excellent :+1: 

And maybe for the next release the whole repo: because than you can link to github https://github.com/NuTyX//NuTyX-Linux   or what ever..

**Comment by tnut** [comment]
Hmm for the houaphan project, I think it can stay. Need some more time of reflexion anyway

**Comment by tnut** [comment]
I guess current or nutyx or core

**Comment by peter1000** [comment]
I would go with: `nutyx` or `NuTyX-Linux`  develop it on the master branch and just make releases as **NuTyX 10.0**

Internally use a variable for any *code-name* if you really want such.

than there is a fix github place one can link to in the documentation.

**Comment by tnut** [comment]
My arguments for calling houphan -> core:
* base,cli and gui are for me the core of a NuTyX OS (even more cli and gui are optionnals)
* extra collections are the "extension" of they respective core collections
* Every collections under github/NuTyX are .. nutyx related 
* current is not good because ALL the collections (if  you stick to master branch) are current

**Comment by peter1000** [comment]
Personally I do not think the argument convincing.

`houphan` is really all one needs to install NuTyX:  If I remember correctly it said at the end: something like:

```
Thank you for installing NuTyX
Have fun!
```

In the end, I really don't care too much about the name - just thought it would be nicer in the documentation and if one *forks* it  - the repo is only called **core** instead of something like **NuTuX-Linux**.

But as long as the name does not change from release to release the documentation links and commands should be easier to maintain for you.

But rethink about what I said of a **fork*

**Comment by tnut** [comment]
The prob of the name of the repo is the same for all of them.
core, extra, xfce4, gnome, kde5, lxde, etc

Since the name won't change anymore and you don't care(which facilitate my choice), it's for me clear the best choice is core

**Comment by peter1000** [comment]
excellent :+1:

**Comment by tnut** [comment]
Git "houaphan" renamed to "core", I adjust the doc every where now. I decide to do because I have the godd feeling this houaphan is the final concept for NuTyX. Will not change anymore.

**Comment by peter1000** [comment]
Sounds good - even if you change the concept, having an independent name will make maintenance of the documentation (especially links) much easier.

Very good.
