### ISSUE TITLE
scripts/apps should be multilingua

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#19]
1. #
e.g. the [nu command](https://github.com/NuTyX/houaphan/blob/master/basicfs/rootfs/bin/nu) should not only be in french.

Take a look at the: [EvoLutionLinux/lution-ais](https://github.com/EvoLutionLinux/lution-ais) which seems to have an easy way to support multiple languages.
 [main file](https://github.com/EvoLutionLinux/lution-ais/blob/master/lution-ais)

Closely related the [ Architect Linux beta Live Installer for Arch Linux ](https://sourceforge.net/projects/architect-linux/)

Something similar to support languages would be also an option for the **NuTyX** installer.

Just an idea ?

**Comment by tnut** [comment]
I will sometimes modify it. Actually it's not that complicate. I have to make like setup-nutyx

**Comment by peter1000** [comment]
just saw `setup-nutyx`: will later fix some of the german
