### ISSUE TITLE
Question: Xfce4 iso

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#22]
* I generated my customized iso: (The one from your webpage gave me errors and would not start).
* I installed a Xfce4 desktop: Installation worked very good.

**Next (tomorrow)** I would like to create a customized iso with and XFCE4 desktop and firefox, geany ... 

Do you have any suggestion?

* start like a normal iso
* in chroot install extra packages
* disable the "setup-nutyx" from starting automatically
* start lxdm automatically

???

Or does something like that already exist. I would like to use it as a Live-USB-Stick for emergency/recovery as well as for installing 'NuTyX'.

QUESTION: is there an option to include the base installation packages directly in the iso: So that one could install NuTyX on multiple computers without internet connection?

Cheers
P

**Comment by tnut** [comment]
This does not exist yet as it is quite easy to do as you mentionned. Now the question, is it bug free that's another question.   About the question include the base installation packages directly in the iso, may I understand wrong but install-houaphan does it or then I did get your question

**Comment by peter1000** [comment]
Question @tnut: 

How do you generate: http://downloads.nutyx.org/NuTyX_x86_64-8-0-xfce-4.12.3.iso

I would like to re-do it myself.

**Comment by tnut** [comment]
For this, I will have to try and put down every steps, I remember they are a few tricky ones

**Comment by peter1000** [comment]
**That would be very kind of you** - probably you could have on your Webpage or here on github a *Wiki* with *tips & tricks*.

If you write down the basic steps, I can write an English installation guide when I try it (if you want).

**Comment by peter1000** [comment]
I would **very much like** it if you could write down the basic steps: How do you generate: http://downloads.nutyx.org/NuTyX_x86_64-8-0-xfce-4.12.3.iso

**Comment by tnut** [comment]
I try this we, but I cannot promist you as it look like a major release of LFS is coming soon. I'm working on that and also polishing the existing documentation. Still somes parts that coulds be completed

**Comment by tnut** [comment]
will try this werk even If my motivation is back
