### ISSUE TITLE
Clarify possible values for: PKGMK_GROUPS

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#28]
example <https://github.com/NuTyX/houaphan/blob/cc24b8bb82134e480e73356558db170041073409/base/bison/Pkgfile#L11>

```
PKGMK_GROUPS=(man locale)
```

But `man pkgmk.conf` says: **Possible values: '(lib devel man doc service)'**

```
       PKGMK_GROUPS=('STRING1' .. 'STRINGN')
              If set, pkgmk will  try  to  split  the  produced  package  into
              groups.  Each  group is define in this variable. A default func‐
              tion is executed if this same function is not found in the  Pkg‐
              file.
              Default:  '()'  No sub package will be produced except if define
              in the Pkgfile Possible values: '(lib devel man doc service)'
```

**Comment by tnut** [comment]
I don't really understand what's you mean: Possible values are: (lib devel man doc service)
but if you want to "force" to have only certains sub packages (kernel is a good example) you specify which one you want in the Pkgfile file

**Comment by peter1000** [comment]
I think in that case **man pkgmk.conf** needs to be changed otherwise it is confusing for someone who actually reads the documentation.

So does that mean I **can but there anything I want**:  e.g. `PKGMK_GROUPS=(audiogroup, lib, graphic)`?

**Comment by tnut** [comment]
Yes  I see what you means, will improve the text
