### ISSUE TITLE
[ARM] Quelques soucis

### ISSUE THREAD

**Issue by Pierre-NuTyX** [NuTyX/core#35]
Bonjour,

J'ai donc commencer à suivre le tuto et lancer nutyx-arm-1.sh

> root [ ~ ]# ./nutyx-arm-1.sh
> ./nutyx-arm-1.sh: line 5: syntax error near unexpected token `newline'
> ./nutyx-arm-1.sh: line 5:`<!DOCTYPE html>'
> root [ ~ ]#

J'attends les modifs du tuto ou des scripts pour reprendre.
Le but étant de prendre le tuto du début à la fin tel quel et arriver au bout :-)

**Comment by tnut** [comment]
L'explication doit être corrigé, en effet si l'on téàlécharge les fichiers comme expliqué on aura tout le fichier formater html. La solution c'est d'utiliser les scripts dispo ds le git

**Comment by Pierre-NuTyX** [comment]
Ok vu, je reprends

**Comment by tnut** [comment]
cp: cannot stat 'glibc.locales.supported': No such file or directory
cp: cannot stat 'blfs-bootscripts': No such file or directory
D'où vienent ces fichiers ?

**Comment by tnut** [comment]
Ok vu pour glibc.locales.supported il est  dans le ports glibc

**Comment by berlius** [comment]
Le souci "html" viens du fait que la page n'est pas vraiment en ligne sur un serveur mais seulement dans le git pour l'instant. Dès qu'elle sera vraiment en ligne le navigateur proposera automatiquement la sauvegarde au format "raw' "txt"  

    On Saturday, March 5, 2016 8:07 PM, tnut <notifications@github.com> wrote:
 

 Ok vu pour glibc.locales.supported il est dans le ports glibc—
