### ISSUE TITLE
python3 setuptools packaging

### ISSUE THREAD

**Issue by kianby** [NuTyX/core#36]
It sounds strange that Python 3 setuptools is part of "gnome". 
- (cli) python-setuptools 6.0.2 Easily download, build, install, upgrade, and uninstall Python packages
- (gnome) python3-setuptools 20.1.1 Easily download, build, install, upgrade, and uninstall Python packages 

Is it an an issue?

**Comment by tnut** [comment]
WIll look at it for me should not be in gnome3

**Comment by peter1000** [comment]
see earlier issue: https://github.com/NuTyX/gnome/issues/4

**Comment by tnut** [comment]
fixed
