### ISSUE TITLE
cli-arm est-ce vraiment un bon choix de nom

### ISSUE THREAD

**Issue by tnut** [NuTyX/core#40]
Je me dis que les paquets qui se trouvent dans cette collection sont en faît des versions statiques des même paquets se trouvant dans la collection cli. Ne serait-il pas plus judicieux de renommer la collection cli-arm en cli-static

**Comment by berlius** [comment]
pas de problème, tu structures comme tu veux, c'est d'ailleurs pour cela que j'avais demandé avant de faire les "commits"  mais où mettre alors  "uboot-tools" qui lui n'est pas "static"
 

    On Sunday, March 6, 2016 6:45 PM, tnut <notifications@github.com> wrote:
 

 Je me dis que les paquets qui se trouvent dans cette collection sont en faît des versions statiques des même paquets se trouvant dans la collection cli. Ne serait-il pas plus judicieux de renommer la collection cli-arm en cli-static—

**Comment by tnut** [comment]
uboot-tools pourrait aller dans cli-extra non ?
c'est un paquet particulier ?

**Comment by berlius** [comment]
oui par exemple. "uboot-tools" est en fait le programme "mkimage" du bootloader "uboot". Il sert à compiler les parametres de boot de ce dernier. Voici un exemple tiré de la doc "nutyx-arm.html" :fatload mmc 0 0x46000000 zImage
fatload mmc 0 0x49000000 sun7i-a20-olinuxino-lime.dtb
setenv bootargs console=ttyS0,115200 [earlyprintk] root=/dev/mmcblk0p2 rootwait panic=10
bootz 0x46000000 - 0x49000000 

    On Sunday, March 6, 2016 9:15 PM, tnut <notifications@github.com> wrote:
 

 uboot-tools pourrait aller dans cli-extra non ?
c'est un paquet particulier ?—
