### ISSUE TITLE
procédure d'installation d'une nutyx pour les archinuls

### ISSUE THREAD

**Issue by nnnutyx** [NuTyX/core#53]
Procédure d’installation d’une nutyx en dur, stable et fonctionnelle au 15/03/2016
A/
1/ télécharger à cette adresse et graver l’iso 
http://downloads.nutyx.org/NuTyX_x86_64-houaphan-8.0.iso

---

B/
1/ préparation du dd, formater le disque en une seule partition xfs ou autre....pour moi xfs à bien marché

---

C/
1/ install de l'iso seulement la partie installation nous intéresse pour le reste inutile
2/ une fois login,
root
nutyx
nutyx
nouveau mot de passe root et confirmation

check

3/ mise à jour de cards
 cards install -u cards

4/ faire le lien (correctif) suivant en root
su -
cd /etc/rc.d/rc0.d/
ls -s ../init.d/init_single K95init_single
cd /etc/rc.d/rc6.d/
ls -s ../init.d/init_single K95init_single

5/ redémarrer pour voir si tout est ok
reboot
puis log en root et mot de passe que vous venez de créer
6/ 
cards upgrade

7/ installation de xfce4 et du nécessaire au démarrage graphique
get xorg xfce4 xfce4-extra lxdm gvfs

8/ création de l'utilisateur
 nu
choisir utilisateur et mot de passe utilisateur

9/ redémarrer
 reboot

10/ démarrage classique avec log sur utilisateur créé

check
get virtualbox-cli virtualbox firefox thunderbird cli vlc

 (+autres applications de votre choix que vous trouverez  dans cette petite liste:" http://www.nutyx.org/fr/packages.html ")

11/ installation de Extensions pack 
pour utiliser pleinement vbox avec les Extension Pack correspondantes téléchargez à cette adresse:

" http://download.virtualbox.org/virtualbox/5.0.14/Oracle_VM_VirtualBox_Extension_Pack-5.0.14-105127.vbox-extpack "
puis sur un terminal 
sudo thunar 
vous pourrez en graphique installer le pack qui est refusé en utilisateur sans les droits.
une fois installé, les usb2 et usb3 sont fonctionnels.
ce n'est pas la dernière version de virtualbox mais ça dépanne bien quand on en a besoin.

**Comment by tnut** [comment]
Le point 10/ peut être simplifié:

      check
      get virtualbox-cli virtualbox lxdm firefox thunderbird cli vlc

**Comment by tnut** [comment]
Maintenant la question: Où placer ce Topic ? qui se veut direct et concis donc. Je ferai les corrections necessaires sur la page finale. Les suggestions sont le bienvenue

**Comment by Pierre-NuTyX** [comment]
Déjà dans l'iso en install.txt pour avoir le déroulé lors de l'install 
pour ceux qui comme moi ont une petite mémoire :p

**Comment by tnut** [comment]
bonne idée ça et aussi sur le lien http://downloads.nutyx.org/install.txt
