### ISSUE TITLE
layout bunched up (improper spacing) in gui apps

### ISSUE THREAD

**Issue by timcowchip** [NuTyX/core#62]
firefox http://en.zimagez.com/zimage/2016-03-27-1225261024x768scrot.php
roxterm http://en.zimagez.com/zimage/2016-03-27-1226001024x768scrot.php

**Comment by tnut** [comment]
Thanks for the report
On which version of NuTyX do you face this prob and on which arch ?

**Comment by timcowchip** [comment]
NuTyX 8.1-rc2 x86_64

**Comment by tnut** [comment]
Theme issues, cannot fixe it
