### ISSUE TITLE
Clarification: Groups

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#68]
follow up from: https://github.com/NuTyX/core/pull/67

**I think it is important to define what is the purpose of groups variable sharing.**

If it is only for the version: I think one should change the code and source the main group file differently. 

If indeed ALL variables should be shared than why do we have: `if [ -z "$version" ]; then`

```bash
	if [ -z $group ]; then
		group="`echo $name | cut -d "-" -f1`"
	fi
	if [ "$group" == "$name" ]; then
		unset group
	fi
	if [ -z "$version" ]; then
		if [ ! -z "$group" ];then
			if [ -f ../$group/$PKGMK_PKGFILE ];then
				. ../$group/$PKGMK_PKGFILE
				unset run
				. $PKGMK_PKGFILE
			else
				warning "Variable 'version' not initiated or not found in $PKGMK_PKGFILE."
			fi
		else
			warning "Variable 'version' not initiated or not found in $PKGMK_PKGFILE."
		fi
	fi
```

QUESTION: do you remember why the **run** must be unset? https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L1235

**Comment by peter1000** [comment]
hi @tnut,

Any clarification about this? **What should group share: ALL variables or ONLY version?**

1. If it is only for the version: I think one should change the code and source the main group file differently.

2. If indeed ALL variables should be shared than why do we have: `if [ -z "$version" ]; then`

**Comment by tnut** [comment]
they share version , release source in some cases

**Comment by tnut** [comment]
the check of version is afterwards

**Comment by peter1000** [comment]
> they share version , release, and source variables in some cases.

But the current code only does that if no version is set: so if you only want to share source variables that would not work.

Anyway: I guess it would be still good for NuTyX to define that in more details: maybe when you write the Pkgfile info: https://github.com/NuTyX/core/issues/73
