### ISSUE TITLE
Suggestion: Pkgfile.html

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#73]
I think it would be nice for users  if you could write some documentation about the Pkgfile format NuTyX-Linux uses: *maybe a bit similar what you did with the dictionary.html.*

* **I am still a bit confused myself** :-1: 

e.g. which functions are 'officially supported, what is their purpose', run=(), PKGMK_GROUPS,  prepare etc..
* Maybe one could also include some info about the configuration file: from the man pages...

and just put all into one nice `pkgfile.html`

Just an suggestion: **I'm quite willing to re-write it if you want** after you did an initial draft..

**Comment by tnut** [comment]
its a very good idea will do

Thierry

**Comment by peter1000** [comment]
I will add here some ideas you could use:

###     name / pkgname

Valid characters for a pkgname are `alphanumeric`, and any of the following characters: `-_+`. 
Additionally, names MUST start with an alphanumeric character.

**Comment by peter1000** [comment]
### PKGMK_GROUPS array functions

If the configuration variable `PKGMK_GROUPS` is set in the `pkgmk.conf` file or in an individual Pkgfile, pkgmk
will try to split the produced package into additional groups defined in this array.
A default function is executed if a function with the same name is not found in the Pkgfile.
Supported default group functions are: lib() devel() doc() man() service()

**Comment by peter1000** [comment]
I think you made a mistake in the pkgfile.html: e.g. https://github.com/NuTyX/core/blob/master/www/en/pkgfile.html#L60

```
<p>The name of the package cannot contains following charaters: [space] - _ + ? !</p>
```

many pkgnames have for instance: "-"  `ca-certificates`  except you want to change it. Probably you are better off if you use something more closely to what I suggested above.

**release** 
> In case we want to refer a date

Ok now I understand why you allow such a high number :+1:

**Comment by peter1000** [comment]
Any reason you do not allow capital pkg names: if you want to be more compatible with Arch Linux: they allow capital letters: e.g. https://www.archlinux.org/packages/extra/any/libreoffice-fresh-en-ZA/

**Comment by tnut** [comment]
no specific reason for the name
