### ISSUE TITLE
Suggestion: Function names should be in English

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#74]
example: [MiseAJourParNiveau() ](https://github.com/NuTyX/core/blob/master/scripts/CheckBinary#L118)

**Comment by tnut** [comment]
I agreed, be aware this script is obsolet, it's there for info and inspiration

**Comment by peter1000** [comment]
thanks - maybe you should add an info at the top of the script to say it is obsolete or move it to a subfolder?
