### ISSUE TITLE
blfs-bootscripts

### ISSUE THREAD

**Issue by fanch** [NuTyX/core#77]
Pout éviter certains désagrément avec blfs-bootscripts, il serait peut être intéressant d'utiliser ce lien : http://ftp.osuosl.org/pub/blfs/conglomeration/blfs-bootscripts/ ou soit de veiller aux mises à jour de blfs-bootscripts.

NOTA : blfs-bootscripts concerne diverses collections (core, extra,.....).A titre d'exemple, Je viens de procéder à la compilation d'une base et j'ai été bloqué par des adresses de liens le concernant dans la pass2, il s'agit de rsync, gpm et openssh . Pour finir la construction de l'iso, le même blocage concernait rpcbind et nfs-utils.

Je ne voudrais pas que des liens cassés ne dissuadent ou découragent certains testeurs désirant se construire leur propre base de NuTyX.

**Comment by tnut** [comment]
si la version des scripts blfs a changé il faut ajuster le fichier de config. qui est dans install-nutyx. On ne veut pas "rester" sur une version. Cette methode peut engendrer des deagrements mais elle nous informe si la version est obsolète

**Comment by tnut** [comment]
install-nutyx -h pour plus d info

**Comment by fanch** [comment]
Donc, il faut veiller aux mises à jour de blfs-bootscripts. Le site dont je donnais le lien a l'avantage et l'inconvénient de proposer le suivi de l'ensemble des versions de blfs-bootscripts.
Merci pour ta réponse.
PS: ma question et ta réponse devraient éclairer sh4dow^ dans sa construction d'une base NuTyX.

**Comment by tnut** [comment]
l'info se trouve dans /etc/blfs-bootscripts

**Comment by sh4d0w31410** [comment]
Merci a tous les deux, j'ai pu terminer la pass2 grâce a ces modifications. Bon boulot

**Comment by tnut** [comment]
Je peux fermer l'issue je crois que le problème est réglé
