### ISSUE TITLE
Collection - can they be nested

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#84]
https://github.com/NuTyX/core/blob/master/www/en/dictionary.html#L56

I think the dictionary should specify if collections can be nested.

**Example nested collection**

```
/home/root_collection
├── audio_collection
│   ├── audio_port1
│   │   └── Pkgfile
│   └── audio_port2
│       └── Pkgfile
└── desktops_collections
    ├── gnome_collection
    │   ├── gnome_port1
    │   │   └── Pkgfile
    │   └── gnome_port2
    │       └── Pkgfile
    └── xfc4_collection
        ├── xfce4_port1
        │   └── Pkgfile
        └── xfce4_port2
            └── Pkgfile
```

**Is it valid** to specify in `cards.conf`

```
dir /home/root_collection
```

**NOTE** I am not suggesting this - I think it should be just specified.

Personally I think it should not be valid - because it might get messy if there are ports with same names in sub collections.

Maybe it should also mention what makes a collection special: e.g. can it be installed with a simple command, can be registered to not be removed (base-collection) etc..

**Comment by tnut** [comment]
If the name of a port is found twice or more it's going to be the first found in the order that will be used

**Comment by peter1000** [comment]
So it is OK to nest collections like above?

**Comment by tnut** [comment]
I'm not shure. I will need to try

**Comment by tnut** [comment]
At the moment I'm a bit off with NuTyX and Cards. My mainly target now is to enjoy what our team have made so far. I enjoy very much this stable version, of NuTyX means unless security issues, I'm not welling to updade anything for the next fews days (maybe fews weeks)

**Comment by peter1000** [comment]
:+1:
