### ISSUE TITLE
 2 README files  port lxdm

### ISSUE THREAD

**Issue by peter1000** [NuTyX/core#99]
hi

Just something I noticed.
Is there any particularreason of having 2 README files in https://github.com/NuTyX/core/tree/master/gui/lxdm

**Comment by tnut** [comment]
you re. right lxdm.README is the only valid one

**Comment by peter1000** [comment]
**Do I understand that correctly** that there can be also for each group, locale *separate meta files*.

e.g. attr

attr.README,
attr.post-installl

attr.devel.README 
attr.devel.post-installl

attr.fr.README
attr.fr.post-installl

**Comment by peter1000** [comment]
https://github.com/NuTyX/core/pull/102
